---
imap_nickname: FB
imap_server: outlook.office365.com
imap_user: glh@fb.com
imap_keychain_account: glh+mutt@fb.com
imap_keychain_name: office365.com

smtp_server: smtp.office365.com
smtp_from: glh@fb.com
smtp_user: glh@fb.com
smtp_keychain_account: glh+mutt@fb.com
smtp_keychain_name: office365.com
