---
dotfile_files:
  - .ackrc
  - .agignore
  - .alacritty.yml
  - .bash
  - .bash_profile
  - .clipper.json
  - .config/karabiner
  - .config/ranger
  - .emacs.d
  - .ghci
  - .gitattributes
  - .gitignore
  - .gitk
  - .gvimrc
  - .hammerspoon
  - .hgrc
  - .imapfilter
  - .inputrc
  - .lbdbrc
  - .msmtprc
  - .mbsyncrc
  - .mutt
  - .notmuch-config
  - .npmrc
  - .pypirc
  - .rdebugrc
  - .rspec
  - .screenrc
  - .tmux.conf
  - .urlview
  - .vim
  - .zsh
  - .zshenv
  - .zshrc

dotfile_templates:
  - .corpusrc
  - .gemrc
  - .gitconfig

git_user_email: '{{"greg@hurrell.net" if lookup("env", "USER") == "glh" else ""}}'
git_user_name: '{{"Greg Hurrell" if lookup("env", "USER") == "glh" else ""}}'
