---
dotfiles:
  - .ackrc
  - .agignore
  - .bash
  - .bash_profile
  - .clipper.json
  - .emacs.d
  - .ghci
  - .gitattributes
  - .gitconfig
  - .gitignore
  - .gitk
  - .gvimrc
  - .hammerspoon
  - .hgrc
  - .imapfilter
  - .inputrc
  - .lbdbrc
  - .msmtprc
  - .mbsyncrc
  - .mutt
  - .notmuch-config
  - .npmrc
  - .rdebugrc
  - .rspec
  - .screenrc
  - .tmux.conf
  - .urlview
  - .vim
  - .zsh
  - .zshenv
  - .zshrc
