---
dotfile_files:
  - .ackrc
  - .agignore
  - .alacritty.yml
  - .bash
  - .bash_profile
  - .clipper.json
  - .config/karabiner
  - .config/ranger
  - .ghci
  - .gitattributes
  - .gitignore
  - .gitk
  - .gvimrc
  - .hammerspoon
  - .hgrc
  - .imapfilter
  - .inputrc
  - .lbdbrc
  - .mutt
  - .npmrc
  - .pypirc
  - .rdebugrc
  - .rspec
  - .screenrc
  - .tmux.conf
  - .urlview
  - .vim
  - .zsh
  - .zshenv
  - .zshrc

dotfile_templates:
  - .corpusrc
  - .gemrc
  - .gitconfig
  - .imapfilter/config.lua
  - .mbsyncrc
  - .msmtprc
  - .mutt/config/settings.mutt
  - .mutt/hooks/presync.sh
  - .notmuch-config

git_user_email: '{{"greg@hurrell.net" if lookup("env", "USER") == "glh" else ""}}'
git_user_name: '{{"Greg Hurrell" if lookup("env", "USER") == "glh" else ""}}'

imap_nickname: ISP
imap_server: imap.example.com
imap_user: user@example.com
imap_keychain_account: user@example.com
imap_keychain_name: example.com

smtp_server: smtp.example.com
smtp_from: user@example.com
smtp_user: user@example.com
smtp_keychain_account: user@example.com
smtp_keychain_name: example.com
