# base24 Space Gray Eighties Dull 256 - alacritty color config
# FredHappyface (https://github.com/fredHappyface)

# Default colors
[colors.primary]
background = '0x212121'
foreground = '0x9a9fa6'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x212121'
cursor = '0x9a9fa6'

# Normal colors
[colors.normal]
black = '0x15171c'
red = '0xb14956'
green = '0x91b377'
yellow = '0x5485c0'
blue = '0x7b8fa4'
magenta = '0xa5779e'
cyan = '0x7fcccb'
white = '0xb2b8c2'

# Bright colors
[colors.bright]
black = '0x555555'
red = '0xec5f67'
green = '0x88e985'
yellow = '0xfdc253'
blue = '0x5485c0'
magenta = '0xbf83c0'
cyan = '0x58c2c0'
white = '0xffffff'

[[colors.indexed_colors]]
index = 16
color = "0xc6725a"

[[colors.indexed_colors]]
index = 17
color = "0x58242b"

[[colors.indexed_colors]]
index = 18
color = "0x15171c"

[[colors.indexed_colors]]
index = 19
color = "0x555555"

[[colors.indexed_colors]]
index = 20
color = "0x83868b"

[[colors.indexed_colors]]
index = 21
color = "0xb2b8c2"
