---
- name: misc | ensure directories exist
  file: path={{ item }} state=directory
  loop:
    - ~/Archives
    - ~/Local

- name: misc | touch ~/mbox
  file: path=~/mbox state=touch

- name: misc | hide items
  command: chflags hidden {{ item }}
  loop:
    - ~/mbox

- name: misc | install prefnerd
  gem: name=prefnerd user_install=yes

# Note: Won't work without Node (which means homebrew role has to have run
# first, but I don't want to declare an explicit, heavyweight dependency in this
# role).
- name: misc | install global NPM modules
  npm: name={{ item }} global=yes
  loop:
    - bs-platform
    - flow-bin
    - flow-typed
    - gatsby-cli
    - ocaml-language-server
    - reason-cli
    - source-map-explorer
    - typescript
    - typescript-language-server
