---
# Many of these settings taken (or modified) from:

#   https://github.com/mathiasbynens/dotfiles/commits/master/.osx
osx_defaults:
  - read: '-currentHost read NSGlobalDomain AppleFontSmoothing'
    write: '-currentHost write NSGlobalDomain AppleFontSmoothing -int 1'
    expected: '1'
    description: Tweak subpixel font rendering (https://wincent.com/wiki/AppleFontSmoothing)
    last_tested: '10.9'

  - read: '-currentHost read com.apple.screensaver showClock'
    write: '-currentHost write com.apple.screensaver showClock -int 1'
    expected: '1'
    description: System Preferences -> Desktop & Screen Saver -> Screen Saver -> Show with clock
    last_tested: '[10.10.2]'

  - read: '-currentHost read com.apple.screensaver idleTime'
    write: '-currentHost write com.apple.screensaver idleTime -int 300'
    expected: '300'
    description: System Preferences -> Desktop & Screen Saver -> Screen Saver -> Start after -> 5 Minutes
    last_tested: '[10.10.2]'

  - read: read NSGlobalDomain _HIHideMenuBar
    write: write NSGlobalDomain _HIHideMenuBar -int 1
    expected: '1'
    description: System Preferences -> General -> Appearance -> Automatically hide and show the menu bar
    last_tested: '10.11'

  - read: read NSGlobalDomain AppleAquaColorVariant
    write: write NSGlobalDomain AppleAquaColorVariant -int 6
    expected: '6'
    description: System Preferences -> General -> Appearance -> Graphite
    last_tested: '10.10'

  - read: read NSGlobalDomain ApplePressAndHoldEnabled
    write: write NSGlobalDomain ApplePressAndHoldEnabled -bool false
    expected: '0'
    description: Disable press-and-hold for keys in favor of key repeat Requires logout.
    last_tested: '[10.9]'

  - read: read NSGlobalDomain AppleScrollerPagingBehavior
    write: write NSGlobalDomain AppleScrollerPagingBehavior -int 0
    expected: '0'
    description: System Preferences -> General -> Click in scroll bar to -> Jump to the next page
    last_tested: '[10.10.2]'

  - read: read NSGlobalDomain AppleShowAllExtensions
    write: write NSGlobalDomain AppleShowAllExtensions -bool true
    expected: '1'
    description: Finder -> show all filename extensions
    last_tested: '[10.9]'

  - read: read NSGlobalDomain AppleShowScrollBars
    write: write NSGlobalDomain AppleShowScrollBars -string Automatic
    expected: 'Automatic'
    description: System Preferences -> General -> Show scroll bars -> Automatically based on mouse or trackpad
    last_tested: '[10.10.2]'

  - read: read NSGlobalDomain PMPrintingExpandedStateForPrint
    write: write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
    expected: '1'
    description: Expand print panel by default
    last_tested: '[10.9]'

  - read: read NSGlobalDomain PMPrintingExpandedStateForPrint2
    write: write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true
    expected: '1'
    description: Expand print panel by default
    last_tested: '[10.9]'

  - read: read NSGlobalDomain NSAutomaticDashSubstitutionEnabled
    write: write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
    expected: '0'
    description: Disable smart quotes, dashes, ellipses
    last_tested: '[10.9]'

  - read: read NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled
    write: write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
    expected: '0'
    description: Disable smart quotes, dashes, ellipses
    last_tested: '[10.9]'

  - read: read NSGlobalDomain NSAutomaticSpellingCorrectionEnabled
    write: write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
    expected: '0'
    description: Disable auto-correct
    last_tested: '[10.9]'

  - read: read NSGlobalDomain NSCloseAlwaysConfirmsChanges
    write: write NSGlobalDomain NSCloseAlwaysConfirmsChanges -int 0
    expected: '0'
    description: System Preferences -> General -> [Don't] Ask to keep changes when closing documents
    last_tested: '[10.10.2]'

  - read: read NSGlobalDomain NSNavPanelExpandedStateForSaveMode
    write: write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
    expected: '1'
    description: Expand save panel by default
    last_tested: '[10.9]'

  - read: read NSGlobalDomain NSNavPanelExpandedStateForSaveMode2
    write: write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
    expected: '1'
    description: Expand save panel by default
    last_tested: '[10.9]'

  - read: read NSGlobalDomain NSQuitAlwaysKeepsWindows
    write: write NSGlobalDomain NSQuitAlwaysKeepsWindows -int 0
    expected: '0'
    description: System Preferences -> General -> [Don't] Close windows when quitting an app
    last_tested: '[10.10.2]'

  - read: read NSGlobalDomain NSTableViewDefaultSizeMode
    write: write NSGlobalDomain NSTableViewDefaultSizeMode -int 1
    expected: '1'
    description: System Preferences -> General -> Sidebar icon size -> Small
    last_tested: '[10.10.2]'

  - read: read NSGlobalDomain NSWindowResizeTime
    write: write NSGlobalDomain NSWindowResizeTime -float 0.001
    expected: '0.001'
    description: Make sheets drop down (almost) instantly
    last_tested: '[10.10.2]'

  - read: read NSGlobalDomain com.apple.sound.beep.feedback
    write: write NSGlobalDomain com.apple.sound.beep.feedback -bool false
    expected: '0'
    description: System Preferences -> Sound -> Sound Effects -> Play feedback when volume is changed
    last_tested: '[10.10.2]'

  - read: read NSGlobalDomain com.apple.springing.delay
    write: write NSGlobalDomain com.apple.springing.delay -float 0
    expected: '0'
    description: Finder -> Preferences -> General -> Spring-loaded folders and windows -> Delay (short)
    last_tested: '[10.10.2]'

  - read: read NSGlobalDomain com.apple.springing.enabled
    write: write NSGlobalDomain com.apple.springing.enabled -bool true
    expected: '1'
    description: Finder -> Preferences -> General -> Spring-loaded folders and windows
    last_tested: '[10.10.2]'

  - read: read com.apple.dock wvous-bl-corner
    write: write com.apple.dock wvous-bl-corner -int 5
    expected: '5'
    description: System Preferences -> Desktop & Screen Saver -> Screen Saver -> Hot Corners -> [Bottom Left] Start Screen Saver
    last_tested: '[10.10.2]'

  - read: read com.apple.dock wvous-tr-corner
    write: write com.apple.dock wvous-tr-corner -int 6
    expected: '6'
    description: System Preferences -> Desktop & Screen Saver -> Screen Saver -> Hot Corners -> [Top Right] Disable Screen Saver
    last_tested: '[10.10.2]'

  - read: read com.apple.finder _FXShowPosixPathInTitle
    write: write com.apple.finder _FXShowPosixPathInTitle -bool false
    expected: '0'
    description: Don't display full POSIX path as Finder window title
    last_tested: '[10.9]'

  - read: read com.apple.finder DisableAllAnimations
    write: write com.apple.finder DisableAllAnimations -bool true
    expected: '1'
    description: Finder -> disable window animations and Get Info animations
    last_tested: '[10.9]'

  - read: read com.apple.finder FXEnableExtensionChangeWarning
    write: write com.apple.finder FXEnableExtensionChangeWarning -bool false
    expected: '0'
    description: Disable the warning when changing a file extension
    last_tested: '[10.9]'

  - read: read com.apple.finder QLEnableTextSelection
    write: write com.apple.finder QLEnableTextSelection -bool true
    expected: '1'
    description: Finder -> allow text selection in Quick Look
    last_tested: '[10.9]'

  - read: read com.apple.finder QuitMenuItem
    write: write com.apple.finder QuitMenuItem -bool true
    expected: '1'
    description: Finder -> allow quitting via Command-Q; doing so will also hide desktop icons
    last_tested: '[10.9]'

  - read: read com.apple.finder ShowPathbar
    write: write com.apple.finder ShowPathbar -bool true
    expected: '1'
    description: Finder -> show path bar
    last_tested: '[10.9]'

  - read: read com.apple.finder ShowStatusBar
    write: write com.apple.finder ShowStatusBar -bool true
    expected: '1'
    description: Finder -> show status bar
    last_tested: '[10.9]'

  - read: read com.apple.print.PrintingPrefs "Quit When Finished"
    write: write com.apple.print.PrintingPrefs "Quit When Finished" -bool true
    expected: '1'
    description: Automatically quit printer app once the print jobs complete
    last_tested: '10.9'

  - read: read com.apple.recentitems RecentApplications
    write: write com.apple.recentitems RecentApplications -dict-add MaxAmount 50
    expected: '50' # can't read a value from a nested dictionary, always updates
    description: System Preferences -> General -> Recent items
    last_tested: '[10.10.2]'

  - read: read com.apple.recentitems RecentDocuments
    write: write com.apple.recentitems RecentDocuments -dict-add MaxAmount 50
    expected: '50' # can't read a value from a nested dictionary, always updates
    description: System Preferences -> General -> Recent items
    last_tested: '[10.10.2]'

  - read: read com.apple.recentitems RecentServers
    write: write com.apple.recentitems RecentServers -dict-add MaxAmount 50
    expected: '50' # can't read a value from a nested dictionary, always updates
    description: System Preferences -> General -> Recent items
    last_tested: '[10.10.2]'

  - read: read com.apple.screensaver askForPassword
    write: write com.apple.screensaver askForPassword -int 1
    expected: '1'
    description: Require password immediately after sleep or screen saver begins
    last_tested: '[10.9]'

  - read: read com.apple.screensaver askForPasswordDelay
    write: write com.apple.screensaver askForPasswordDelay -int 0
    expected: '0'
    description: Require password immediately after sleep or screen saver begins
    last_tested: '[10.9]'

  - read: read com.apple.TextEdit RichText
    write: write com.apple.TextEdit RichText -int 0
    expected: '0'
    description: Use plain text mode for new TextEdit documents
    last_tested: '[10.9]'

  - read: read com.apple.universalaccess reduceTransparency
    write: write com.apple.universalaccess reduceTransparency -bool true
    expected: '1'
    description: System Preferences -> Accessibility -> Display -> Reduce Transparency
    last_tested: '10.10'

  - read: read com.googlecode.iterm2 AdjustWindowForFontSizeChange
    write: write com.googlecode.iterm2 AdjustWindowForFontSizeChange -bool false
    expected: 0
    description: iTerm2 -> Preferences -> General -> Adjust window when changing font size
    last_tested: '2.9.20150224-nightly'

  - read: read com.googlecode.iterm2 HideActivityIndicator
    write: write com.googlecode.iterm2 HideActivityIndicator -bool true
    expected: 1
    description: iTerm2 -> Preferences -> Appearance -> Hide tab activity indicator
    last_tested: '2.9.20150224-nightly'

  - read: read com.googlecode.iterm2 HideScrollbar
    write: write com.googlecode.iterm2 HideScrollbar -bool true
    expected: 1
    description: iTerm2 -> Preferences -> Appearance -> Hide scrollbars
    last_tested: '2.9.20150224-nightly'

  - read: read com.googlecode.iterm2 OptimumTabWidth
    write: write com.googlecode.iterm2 OptimumTabWidth -int 275
    expected: 275
    description: iTerm2 -> Preferences -> Advanced -> Tabs: Preferred tab width
    last_tested: '2.9.20150224-nightly'

  - read: read com.googlecode.iterm2 UseLionStyleFullscreen
    write: write com.googlecode.iterm2 UseLionStyleFullscreen -bool false
    expected: 0
    description: iTerm2 -> Preferences -> General -> Native full screen windows
    last_tested: '2.9.20150224-nightly'
